- name: docker
  hosts: docker
  become: true

  tasks:
    - name: Upgrade all packages
      dnf:
        name: "*"
        state: latest

    - name: Enabling EPEL Release
      dnf:
        name: epel-release
        state: present

    - name: Enable docker-ce repository
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Installing docker-ce
      dnf:
        name: "{{ item }}"
        state: latest
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin

    - name: Enabling Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
