- name: zabbix-agent
  hosts: zabbix-agent
  become: yes
  become_user: root
  vars:
    zabbix_server: 172.16.2.91

  tasks:
    - name: get Zabbix 6.1.2
      shell:
        cmd: rpm -Uvh https://repo.zabbix.com/zabbix/6.1/rhel/8/x86_64/zabbix-release-6.1-2.el8.noarch.rpm
      ignore_errors: yes

    - name: clean DNF cache
      shell:
        cmd: dnf clean all

    - name: installing Zabbix agent and its dependencies
      dnf:
        name: "{{ item }}"
        state: latest
      with_items:
        - zabbix-agent2
        - zabbix-selinux-policy

    - name: configurations on /etc/zabbix/zabbix_agent2.conf
      lineinfile:
        dest: /etc/zabbix/zabbix_agent2.conf
        state: present
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backrefs: yes
      with_items:
        - { regexp: '^Server=.+', line: "Server={{ zabbix_server }}" }
        - { regexp: '^ServerActive=.+', line: "ServerActive={{ zabbix_server }}" }
        - { regexp: '^Hostname=.+', line: "Hostname={{ hostvars[inventory_hostname].ansible_hostname }}" }

    - name: add zabbix-agent service permanent on firewall-cmd
      shell:
        cmd: firewall-cmd --add-service=zabbix-agent --permanent

    - name: reload firewall-cmd
      shell:
        cmd: firewall-cmd --reload

    - name: starting and enabling zabbix-agent
      systemd:
        name: zabbix-agent2
        state: restarted
        enabled: yes

    - name: SELinux policies
      shell:
        cmd: "{{ item }}"
      with_items:
        - setsebool -P httpd_can_network_connect 1
        - setsebool -P httpd_can_connect_zabbix 1
        - setsebool -P zabbix_can_network 1
