- name: zabbix-server
  hosts: all
  become: true
  vars:
    zabbix_db_password: put_your_password_here
    zabbix_db_server: 172.16.2.92

  tasks:
    - name: get Zabbix 6.1.2
      shell:
        cmd: rpm -Uvh https://repo.zabbix.com/zabbix/6.1/rhel/8/x86_64/zabbix-release-6.1-2.el8.noarch.rpm
      ignore_errors: yes

    - name: clean DNF cache
      shell:
        cmd: dnf clean all

    - name: installing Remi repository for PHP 7.4
      dnf:
        name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
        state: latest
        disable_gpg_check: yes

    - name: reseting php module
      shell:
        cmd: dnf module reset -y php

    - name: enable remi-7.4
      shell:
        cmd: dnf module enable -y php:remi-7.4

    - name: installing Zabbix and its dependencies
      dnf:
        name: "{{ item }}"
        state: latest
      with_items:
        - zabbix-server-mysql
        - zabbix-web-mysql
        - zabbix-nginx-conf
        - zabbix-sql-scripts
        - zabbix-selinux-policy
        - zabbix-agent2
        - php74-php-fpm
        - php
        - php-cli
        - php-common
        - php-gd
        - php-bcmath
        - php-mbstring
        - php-xml
        - php-ldap
        - php-json
        - mysql

    - name: configurations on /etc/zabbix/zabbix_server.conf
      lineinfile:
        dest: /etc/zabbix/zabbix_server.conf
        state: present
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backrefs: yes
      with_items:
        - { regexp: '# DBPassword=', line: "DBPassword={{ zabbix_db_password }}" }
        - { regexp: '# DBHost=localhost', line: "DBHost={{ zabbix_db_server }}" }

    - name: starting and enabling zabbix-server
      systemd:
        name: zabbix-server
        state: restarted
        enabled: yes

    - name: starting and enabling zabbix-agent
      systemd:
        name: zabbix-agent
        state: restarted
        enabled: yes

    - name: add zabbix-agent service permanent on firewall-cmd
      shell:
        cmd: firewall-cmd --add-service=zabbix-agent --permanent

    - name: add zabbix-server service permanent on firewall-cmd
      shell:
        cmd: firewall-cmd --add-service=zabbix-server --permanent

    - name: reload firewall-cmd
      shell:
        cmd: firewall-cmd --reload

    - name: SELinux setsebool -P httpd_can_network_connect_db 1
      shell:
        cmd: setsebool -P httpd_can_network_connect_db 1

    - name: vhost nginx zabbix.yourdomain.com.conf
      blockinfile:
        path: /etc/nginx/conf.d/zabbix.yourdomain.com.conf
        block: |
          server {
            listen 80;

            server_name zabbix.yourdomain.com;

            client_max_body_size 5m;
            client_body_buffer_size 128k;

            root /usr/share/zabbix;

            index index.php;

            location = /favicon.ico {
              log_not_found   off;
            }

            location / {
              try_files $uri $uri/ =404;
            }

            location /assets {
              access_log off;
              expires 10d;
            }

            location ~ /\.ht {
              deny all;
            }

            location ~ /(api\/|conf[^\.]|include|locale) {
              deny all;
              return 404;
            }

            location /vendor {
              deny all;
              return 404;
            }

            location ~ [^/]\.php(/|$) {
              fastcgi_pass unix:/run/php-fpm/zabbix.sock;
              fastcgi_split_path_info ^(.+\.php)(/.+)$;
              fastcgi_index index.php;

              fastcgi_param DOCUMENT_ROOT   /usr/share/zabbix;
              fastcgi_param SCRIPT_FILENAME /usr/share/zabbix$fastcgi_script_name;
              fastcgi_param PATH_TRANSLATED /usr/share/zabbix$fastcgi_script_name;

              include fastcgi_params;
              fastcgi_param  QUERY_STRING  $query_string;
              fastcgi_param  REQUEST_METHOD $request_method;
              fastcgi_param  CONTENT_TYPE $content_type;
              fastcgi_param  CONTENT_LENGTH $content_length;

              fastcgi_intercept_errors on;
              fastcgi_ignore_client_abort off;
              fastcgi_connect_timeout 60;
              fastcgi_send_timeout 180;
              fastcgi_read_timeout 180;
              fastcgi_buffer_size 128k;
              fastcgi_buffers 4 256k;
              fastcgi_busy_buffers_size 256k;
              fastcgi_temp_file_write_size 256k;
            }

            location ~*  \.(jpg|jpeg|png|gif|css|js|ico)$ {
              expires max;
              log_not_found off;
            }

            location ~ /\.ht {
              deny all;
            }

            location ~ /\. {
              deny all;
            }

            access_log  /var/log/nginx/zabbix.fcl.com.br_access.log;
            error_log  /var/log/nginx/zabbix.fcl.com.br_error.log;
          }

    - name: php-fpm configuration zabbix.conf
      blockinfile:
        path: /etc/php-fpm.d/zabbix.conf
        block: |
          [zabbix]
          user = apache
          group = apache

          listen = /run/php-fpm/zabbix.sock
          listen.acl_users = apache,nginx
          listen.allowed_clients = 127.0.0.1

          pm = dynamic
          pm.max_children = 50
          pm.start_servers = 5
          pm.min_spare_servers = 5
          pm.max_spare_servers = 35
          pm.max_requests = 200

          php_value[session.save_handler] = files
          php_value[session.save_path] = /var/lib/php/session

          php_value[max_execution_time] = 300
          php_value[memory_limit] = 512M
          php_value[post_max_size] = 100M
          php_value[upload_max_filesize] = 50M
          php_value[max_input_time] = 300
          php_value[max_input_vars] = 10000

    - name: starting and enabling nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes

    - name: starting and enabling php-fpm
      systemd:
        name: php-fpm
        state: restarted
        enabled: yes
